# Generated by Django 4.2 on 2023-04-30 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu2', '0002_menu2_joined_date_menu2_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='menu2',
            new_name='MENU',
        ),
    ]
